# Generated by Django 4.0.3 on 2022-04-17 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabrLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('habr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.habr', verbose_name='Ссылка на хабр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ссылка на пользователя')),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'лайки',
                'db_table': 'habr_like',
            },
        ),
    ]
