# Generated by Django 4.0.4 on 2022-05-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='habr',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='habr_views', to='mainapp.ip'),
        ),
    ]
