# Generated by Django 4.0.4 on 2022-06-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_habr_habr_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='habr',
            name='is_ask_published',
            field=models.BooleanField(default=False, verbose_name='Запрошена публикация'),
        ),
    ]
