# Generated by Django 4.0.3 on 2022-04-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_habrlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='habr',
            name='status',
            field=models.IntegerField(choices=[(1, 'Черновик'), (2, 'Одобрено'), (3, 'Отказано')], default=1, verbose_name='Статус модерирования'),
        ),
    ]
