# Generated by Django 4.0.4 on 2022-05-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_ip_habr_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='habr',
            name='habr_view',
            field=models.PositiveIntegerField(default=0, verbose_name='просмотров'),
        ),
    ]
