# Generated by Django 4.0.3 on 2022-04-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_habr_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habrlike',
            options={'verbose_name': 'habrlike', 'verbose_name_plural': 'habrlikes'},
        ),
    ]
