# Generated by Django 4.0.4 on 2022-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_habr_views_delete_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habr',
            name='habr_view',
            field=models.IntegerField(default=1, verbose_name='просмотров'),
        ),
    ]
