# Generated by Django 4.0.4 on 2022-04-30 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_alter_like_options_remove_like_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habr',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
