# Generated by Django 4.0.3 on 2022-04-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppFunction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор функции')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название функции')),
                ('description', models.TextField(blank=True, verbose_name='Описание функции')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'функция',
                'verbose_name_plural': 'функции',
                'db_table': 'app_function',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AppRole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор роли')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание роли')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
                'db_table': 'app_role',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoleFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.appfunction', verbose_name='Ссылка на функцию')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.approle', verbose_name='Ссылка на роль')),
            ],
            options={
                'verbose_name': 'связь функций и ролей',
                'db_table': 'role_function',
                'ordering': ['role', 'function'],
                'unique_together': {('role', 'function')},
            },
        ),
    ]
