# Generated by Django 4.0.3 on 2022-04-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=128, verbose_name='теги'),
        ),
    ]
