name: Django CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: '84.201.185.83'
    - name: Deploy with rsync
      run: rsync -av -e "ssh -i ~/.ssh/id_rsa" ./Habr miraving2@84.201.185.83:/home/miraving2/code
      
